# Question

Print all elements in sorted order from row and column wise matrix.

Input: mat = [[10,20,30,40],<br>
              [15,25,35,45],<br>
              [27,29,37,48],<br>
              [32,33,39,50]]<br>
          
Output: 10,15,20,25,27,29,30,32,33,35,37,39,40,45,48,50

In [1]:
mat_ele=list(map(int,input().split()))
mat_ele.sort()

10 20 30 40 15 25 35 45 27 29 37 48 32 33 39 50


In [2]:
mat_ele

[10, 15, 20, 25, 27, 29, 30, 32, 33, 35, 37, 39, 40, 45, 48, 50]

# Question

Mirror of matrix across diagonals.

Input: 1 2 4<br>
       5 9 0<br>
       3 1 7<br>
       
Output: 1 5 3<br>
        2 9 1<br>
        4 0 7<br>

In [3]:
import numpy as np
r,c=list(map(int,input().split()))
matrix=list(map(int,input().split()))
arr=np.array(matrix).reshape(r,c)
print(arr.T)

3 3
1 2 4 5 9 0 3 1 7
[[1 5 3]
 [2 9 1]
 [4 0 7]]


# Question

Find if there is a rectangle in binary matrix with corners as 1.

Input: 1 0 1 1 0<br>
       0 0 0 0 1<br>
       0 0 0 1 0<br>
       1 0 1 0 1<br>

Output: Yes
        1 0 1<br>
        0 0 0<br>
        0 0 0<br>
        1 0 1<br>

In [5]:
#general approach
import numpy as np
r,c=int(input()),int(input())
mat=list(map(int,input().split()))
arr=np.array(mat).reshape(r,c)
li=[]
for i in range(0,r):
    for j in range(0,c):
        if arr[i,j]==1:
            li.append((i,j))
print(li)

4
5
1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1
[(0, 0), (0, 2), (0, 3), (1, 4), (2, 3), (3, 0), (3, 2), (3, 4)]


In [12]:
from itertools import combinations
for item in combinations(li,4):
    item=list(item)
    item.sort()
    a,b,c,d=item
    dist1=(abs(a[0]-b[0])**2+abs(a[1]-b[1])**2)**0.5
    dist2=(abs(b[0]-c[0])**2+abs(b[1]-c[1])**2)**0.5
    dist3=(abs(c[0]-d[0])**2+abs(c[1]-d[1])**2)**0.5
    dist4=(abs(a[0]-d[0])**2+abs(a[1]-d[1])**2)**0.5
    if (dist1==dist3 and dist2==dist4) and (dist1!=dist2!=dist3!=dist4):
        print(a,b,c,d,'Yes')
        break

(0, 0) (0, 2) (3, 0) (3, 2) Yes


# Question

You are given an array of n integers find the elements which are repeated more than n/3 times. If there are no such elements print -1.

Input: 1 2 3 1 1

Output: 1


In [16]:
from collections import Counter
li=list(map(int,input().split()))
n=len(li)
di=dict(Counter(li))
li=[key for key,value in di.items() if value>n/3]
if len(li)==0:
    print(-1)
else:
    print(li)

1 2 3 4 5
-1


# Question

Calculate the maximum product of 4 adjacent elements in a matrix.

Input: n = 4<br>
       6, 2, 3, 4<br>
       5, 4, 3, 1<br>
       7, 4, 5, 6<br>
       8, 1, 3, 0<br>

In [32]:
import numpy as np
n=int(input())
li=list(map(int,input().split()))   
arr=np.array(li).reshape(n,n)
prod=[]
for i in range(0,n):
    li=list(arr[i,:])
    if len(li)<=4:
        prod.append(li[0]*li[1]*li[2]*li[3])
    else:
        for j in range(0,len(li)-4):
            prod.append(li[j+0]*li[j+1]*li[j+2]*li[j+3])
    li=list(arr[:,i])
    if len(li)<=4:
        prod.append(li[0]*li[1]*li[2]*li[3])
    else:
        for j in range(0,len(li)-4):
            prod.append(li[j+0]*li[j+1]*li[j+2]*li[j+3])
li=np.diagonal(arr)
if len(li)<=4:
    prod.append(li[0]*li[1]*li[2]*li[3])
else:
    for j in range(0,len(li)-4):
        prod.append(li[j+0]*li[j+1]*li[j+2]*li[j+3])
sec_arr=np.flipud(arr)
li=np.diagonal(sec_arr)
if len(li)<=4:
    prod.append(li[0]*li[1]*li[2]*li[3])
else:
    for j in range(0,len(li)-4):
        prod.append(li[j+0]*li[j+1]*li[j+2]*li[j+3])
print(prod)
print(max(prod))

5
1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 1 0 9 6 4 2 3
[24, 84, 3024, 336, 120, 864, 504, 180, 432, 0, 28, 2592]
3024
