In [19]:
#A revision to sql in database

import sqlite3
con=sqlite3.connect('mysample1.db')
cur=con.cursor()
cur.execute("drop table Emp;")
cur.execute("create table Emp(Name varchar(20) not null, age int(3) not null);")
print("Enter the employee name and age")
name,age=input(),int(input())
print(f'insert into Emp(Name,age) values("{name}",{age});')
cur.execute(f'insert into Emp(Name,age) values("{name}",{age});')
#I update the name="aditya" age to enter input age
age=int(input())
cur.execute(f'update Emp set age={age} where name="{name}";')
cur.execute("select * from Emp;")
for item in cur.fetchall():
    print(item)
con.commit()
con.close()

Enter the employee name and age
aditya
33
insert into Emp(Name,age) values("aditya",33);
100
('aditya', 100)


# Question 1

Given an array of integers. Find out the number which is repeated only once while the rest are repeated thrice in the array. Find that single one.<br>

Input: [2,2,2,3].<br>
Output: 3<br>

Input: [0,1,0,99,1,0,1,]<br>
Output: 99

In [27]:
array=list(map(int,input().split()))
print((sum(set(array))*3 - sum(array))//2)

0 1 0 99 1 0 1
99


# Question 2

Suppose an array is sorted in ascending order is rotated at some pivot unknown to you before hand i.e. [0,1,2,4,5,6,7]. This mifht become [4,5,6,7,0,1,2]. Find the minimum element assume no duplicate element exist.<br>

Input: [3,4,5,1,2]<br>
Output: 1<br>
Input: [4,5,6,7,0,1,2]<br>
Output: 0<br>

In [29]:
#rotation changes the minuimum element position not the minimum element value
arr=list(map(int,input().split()))
print(min(arr))

4 5 6 7 0 1 2
0


# Question 3

Given an positive integer n. generate a square matrux filled with elements 1 to n^2 in a spiral order<br>

Input: 3<br>
Output: [<br>
[1,2,3]<br>
[8,9,4]<br>
[7,5,6]<br>
]<br>

In [75]:
#Reference : https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/
# Function for printing matrix in spiral 
# form i, j: Start index of matrix, row  
# and column respectively m, n: End index 
# of matrix row and column respectively 
def gfg(arr,i,j,m,n,count): 
    # If i or j lies outside the matrix 
    if (i >= m or j >= n) :
        return; 
    # Print First Row 
    for p in range(i,n):
        arr[i,p]=count
        count+=1
    # Print Last Column 
    for p in range(i+1,m):
        arr[p,n-1]=count
        count+=1
    # Print Last Row, if Last and 
    # First Row are not same 
    if ((m-1) != i):
        for p in range(n-2,j,-1):
            arr[m-1, p]=count
            count+=1
    # Print First Column,  if Last and 
    # First Column are not same 
    if ((n-1) != j):
        for p in range(m-1,i,-1):
            arr[p,j]=count
            count+=1
    gfg(arr, i + 1, j + 1, m - 1, n - 1,count) 
n=int(input())
arr=np.zeros(n**2,dtype=int).reshape(n,n)
gfg(arr, 0, 0, n, n,1)
print(arr)

4
[[ 1  2  3  4]
 [12 13 14  5]
 [11 16 15  6]
 [10  9  8  7]]
