# Question

Implement a function ToLowerCase() that has a string parameter str and returns the same string in lowercase<br>

Input: "Hello"<br>
Output: "hello"<br>
Input: "here"<br>
Output: "here"<br>
Input: "LOVELY"<br>
Output: "lovely"<br>

In [4]:
def ToLowerCase(s):
    return s.lower()
string=input()
print(ToLowerCase(string))

LOVELY
lovely


# Question

Given a string and an integer k, you need to reverse the first k characters for every 2k character counting from the start of the string. It there are less than k characters reverse all of them. If there are less than 2k but greator than k then reverse first half and leave the rest<br>

Input: s='abcdefg' k=2<br>
Output: s='bacdfeg'<br>

In [11]:
string=input()
k=int(input())
for i in range(0,len(string),2*k):
    string=string[0:i]+string[i:i+k][::-1]+string[i+k:i+2*k]+string[i+2*k:]
print(string)

adityavardhanavs
3
idatyaravdhavans


# All Previous Questions before 26April 2020:

Given n pairs of paranthesis. write a program function to generate and print all combinations of well formed paranthesis. <br>

Input: 3<br>
Output: ((()))<br>
        (()())<br>
        (())()<br>
        ()(())<br>
        ()()()<br>

In [24]:
from itertools import permutations
n=int(input())
li=['(']*n+[')']*n
stack=[]
for item in set(permutations(li)):
    l=0
    for i in range(0,len(item)):
        if item[i]=='(':
            stack.append('(')
        else:
            if len(stack)!=0:
                stack.pop()
            else:
                l=1
                break
    if l==0:
        print(''.join(item))

3
()()()
()(())
((()))
(())()
(()())


# Question

Given a string that outputs the largest alphabetical order of all consecutive substrings.<br>

Input: 'ab'<br>
Output: {'a','ab','b'}<br>

In [28]:
from itertools import combinations
string=input()
ans=[]
for i,j in combinations(list(range(0,len(string)+1)),2):
    ans.append(string[i:j])
ans.sort()
print(ans)

ab
['a', 'ab', 'b']


# Question

Print the gollowing pattern<br>
Input:7

In [50]:
n=int(input())
for i in range(1,n):
    print(' '*(n-i),end='')
    print(1,end='')
    print(' '*(2*i-2),end='')
    if i>1:
        print(i)
    else:
        print()
li=[i for i in range(1,n+1)]
li=list(map(str,li))
print(' '.join(li))

9
        1
       1  2
      1    3
     1      4
    1        5
   1          6
  1            7
 1              8
1 2 3 4 5 6 7 8 9


# Question

Given an array of elements. You have to change the elements in such a way that the elements of an array are distinct. If we are replacing any value. The replaced value should be greator than the previous value and after modification, the sum of the elements should be as less as possible. <br>

Input: 1,2,3,4,5,5,5<br>
Output: 1,2,3,4,5,6,7<br>
Input: 1,2,5,7,8,8,7<br>
Output: 1,2,5,7,8,9,10<br>

In [53]:
inp_list=list(map(int,input().split()))
for i in range(1,len(inp_list)):
    if inp_list[i]<=inp_list[i-1]:
        inp_list[i]=inp_list[i-1]+1
print(inp_list)

1 2 5 7 8 8 7
[1, 2, 5, 7, 8, 9, 10]


# Question

Print all jumping numbers smaller than or equal to x.<br>
Input: 105<br>
Output: 0 1 2 3 4 5 6 7 8 9 10 12 21 23 32 34 43 45 54 56 65 67 76 78 87 89 98 101<br>
A number is called a jumping number if all adjacent digits are differ by 1.<br>

In [67]:
inp=int(input())
if inp<11:
    for i in range(1,inp):
        print(i,end=' ')
else:
    li=[i for i in range(1,11)]
    for i in range(12,inp+1):
        val=str(i)
        val=list(map(int,val))
        l=0
        for j in range(0,len(val)-1):
            if abs(val[j+1]-val[j])!=1:
                l=1
        if l==0:
            li.append(i)
    print(li)

10000
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 21, 23, 32, 34, 43, 45, 54, 56, 65, 67, 76, 78, 87, 89, 98, 101, 121, 123, 210, 212, 232, 234, 321, 323, 343, 345, 432, 434, 454, 456, 543, 545, 565, 567, 654, 656, 676, 678, 765, 767, 787, 789, 876, 878, 898, 987, 989, 1010, 1012, 1210, 1212, 1232, 1234, 2101, 2121, 2123, 2321, 2323, 2343, 2345, 3210, 3212, 3232, 3234, 3432, 3434, 3454, 3456, 4321, 4323, 4343, 4345, 4543, 4545, 4565, 4567, 5432, 5434, 5454, 5456, 5654, 5656, 5676, 5678, 6543, 6545, 6565, 6567, 6765, 6767, 6787, 6789, 7654, 7656, 7676, 7678, 7876, 7878, 7898, 8765, 8767, 8787, 8789, 8987, 8989, 9876, 9878, 9898]


# Question

Find the rank of a matrix<br>

Input: [[10,20,10],<br>
[-20,-30,10],<br>
[30,50,0]]<br>
Output: 2<br>

In [71]:
import numpy as np
rows=int(input())
li=[]
for i in range(0,rows):
    li.append(list(map(int,input().split())))
arr=np.array(li)
print(np.linalg.matrix_rank(arr))

3
1 0 0
0 1 0
0 0 1
3


# Question

Check whether reversing a sub array makes a list sorted.

Input: 1 2 5 4 3

Output: Yes 

In [76]:
from itertools import combinations
import copy
arr=list(map(int,input().split()))
i,j,l=0,0,0
for i,j in combinations(list(range(0,len(arr)+1)),2):
    req_arr=copy.deepcopy(arr[i:j])
    req_arr.sort()
    if req_arr!=arr[i:j]:
        new_arr=arr[:i]+arr[i:j][::-1]+arr[j:]
        new_arr2=copy.deepcopy(new_arr)
        new_arr2.sort()
        if new_arr2==new_arr:
            l=1
            break
if l==1:
    print("Yes",i+1,j)

1 2 5 4 3 2
Yes 3 6


# Question

Rotate the matrix k times<br>
Input:<br>
N=3 M=3, k=2<br>
[[12,23,34]<br>,[45,56,67]<br>,[78,89,91]]<br>
Output:<br>
[[23,34,12]<br>,[56,67,45]<br>,[89,91,78]]<br>

In [82]:
import numpy as np
n,m,k=list(map(int,input().split()))
mat=[]
for i in range(0,n):
    mat.append(list(map(int,input().split())))
arr=np.array(mat)
for i in range(0,k-1):
    arr=np.concatenate((arr[:,1:],arr[:,0:1]),axis=1)
print(arr)

3 3 2
12 23 31 
45 56 64
78 89 97
[[23 31 12]
 [56 64 45]
 [89 97 78]]


# Question

Find the largest multiple of 3 from the array of digits in o(n) time and o(1) space.<br>

Input: 5 4 3 1 1<br>

Output: 4311<br>

In [88]:
from itertools import combinations
array=list(map(int,input().split()))
if sum(array)%3==0:
    array.sort(reverse=True)
    array=list(map(str,array))
    print(''.join(array))
else:
    val=0
    for i,j in combinations(list(range(0,len(array)+1)),2):
        if sum(array[i:j])%3==0:
            x=array[i:j]
            x.sort(reverse=True)
            x=list(map(str,x))
            x=''.join(x)
            x=int(x)
            if val<x:
                val=x
    print(val)
            

9 8 7 6 5 4 3 2 1 
987654321
